version: '3.8'

services:
    jenkins:
        image: 'jenkins/jenkins:latest'
        container_name: "jenkins"
        ports:
            - '8080:8080'
            - '443:443'
            - '50000:50000'
        volumes:
            - jenkins_data:/var/jenkins_home
            - ~/.ssh/jenkins:/home/jenkins/.ssh
        command: sh -c "curl -L 'https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose \
        && chmod +x /usr/local/bin/docker-compose"
volumes:
    jenkins_data:
    
    
    
