version: '3.8'

services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        container_name: "jenkins"
        ports:
            - '8080:8080'
            - '443:443'
            - '50000:50000'
        volumes:
            - jenkins_data:/var/jenkins_home
            - ~/.ssh/jenkins:/home/jenkins/.ssh
            - /var/run/docker.sock:/var/run/docker.sock         
volumes:
    jenkins_data:
    
    
    
