version: '3.8'

services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        container_name: "jenkins"
        ports:
            - '8080:8080'
            - '443:443'
            - '50000:50000'
            - '3307:3306'
        volumes:
            - jenkins_data:/var/jenkins_home
            - ~/.ssh/jenkins:/home/jenkins/.ssh
            - /var/run/docker.sock:/var/run/docker.sock  
            - /usr/bin/docker:/usr/bin/docker 

    sonarqube:
        image: sonarqube
        container_name: sonarqube
        ports:
            - '9000:9000'
        networks: 
            - sonar-nw
        environment: 
            - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
        volumes: 
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_ext:/opt/sonarqube/extensions
    
    sonardb:
        image: postgres
        networks:
            - sonar-nw
        ports: 
            - '5432:5432'
        environment: 
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        
networks: 
    sonar-nw:
    
volumes:
    jenkins_data:
    sonarqube_data:
    sonarqube_conf:
    sonarqube_logs:
    sonarqube_ext: 
    postgresql:
    postgresql_data:   
    
    
