version: '3.3'

services:            
    influxdb:
        image: influxdb:1.8-alpine
        container_name: influxdb
        restart: always
        env_file:
            - ../.env.docker
        ports:
            - 8086:8086
        volumes:
            - influxdb_data:/var/lib/influxdb
            - ./influx_init.iql:/docker-entrypoint-initdb.d/influx_init.iql
        networks:
            - tigk-nw  

    telegraf:
        image: telegraf:1.21
        container_name: telegraf
        restart: always
        env_file:
            - ../.env.docker
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        environment:
            - HOST_ETC=/hostfs/etc
            - HOST_PROC=/hostfs/proc
            - HOST_SYS=/hostfs/sys
            - HOST_VAR=/hostfs/var
            - HOST_RUN=/hostfs/run
            - HOST_MOUNT_PREFIX=/hostfs
        ports:
            - 8125:8125
        depends_on:
            - influxdb 
        links:
            - influxdb
        networks:
            - tigk-nw  

    grafana:
        image: grafana/grafana-oss:8.2.6
        container_name: grafana-server
        restart: always
        env_file:
            - ../.env.docker
        depends_on:
            - influxdb
        links:
            - influxdb
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - tigk-nw  
        
networks: 
    tigk-nw:
    
volumes:    
    grafana_data:
    influxdb_data:
    
    
