version: '3.3'

services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        container_name: "jenkins"
        env_file:
            - ../.env.docker
        ports:
            - '8080:8080'
            - '443:443'
            - '50000:50000'
            - '3307:3306'
        volumes:
            - jenkins_data:/var/jenkins_home
            - ~/.ssh/jenkins:/home/jenkins/.ssh
            - /var/run/docker.sock:/var/run/docker.sock  
            - /usr/bin/docker:/usr/bin/docker        

    sonarqube:
        image: sonarqube
        container_name: sonarqube
        env_file:
            - ../.env.docker
        ports:
            - '9000:9000'
        networks: 
            - sonar-nw
        volumes: 
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_ext:/opt/sonarqube/extensions
    
    sonardb:
        image: postgres
        networks:
            - sonar-nw
        env_file:
            - ../.env.docker
        ports: 
            - '5432:5432'
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data          
           
networks: 
    sonar-nw:
    
volumes:
    jenkins_data:
    sonarqube_data:
    sonarqube_conf:
    sonarqube_logs:
    sonarqube_ext: 
    postgresql:
    postgresql_data:  
   
    
    
