version: '3.3'

services:
    jenkins:
        build:
            context: ./
        restart: unless-stopped
        container_name: "jenkins"
        env_file:
            - ../.env.docker
        ports:
            - '8080:8080'
            - 443:443
            - 50000:50000
            - 3307:3306
        volumes:
            - jenkins_data:/var/jenkins_home
            - ~/.ssh/jenkins:/home/jenkins/.ssh
            - /var/run/docker.sock:/var/run/docker.sock  
            - /usr/bin/docker:/usr/bin/docker        

    sonarqube:
        image: bitnami/sonarqube:8.9.9
        container_name: sonarqube
        ports:
            - 8081:8080
            - 8443:8443
        networks: 
            - sonar-nw
        volumes: 
            - sonarqube_data:/bitnami/sonarqube
            - ./sonarqube/:/bitnami/sonarqube

    sonardb:
        image: postgres:14
        networks:
            - sonar-nw
        env_file:
            - ../.env.docker
        volumes:
            - postgresql_data:/bitnami/postgresql
            - ./postgresql/:/bitnami/postgresql        
           
networks: 
    sonar-nw:
    
volumes:
    jenkins_data:
    sonarqube_data:
    sonarqube_conf:
    sonarqube_logs:
    sonarqube_ext: 
    postgresql:
    postgresql_data:  
   
    
    
